// Generated by CoffeeScript 1.6.3
(function() {
  var DEBUG, adverb, box, cat, dbg, ex, from, id, insert, iota, noun, plus, qp, qv, rsh, sha, size, st, test, test2, va, val, vd, verb, vm, vt, wd;

  vt = '"+,<{#~';

  plus = function(a, w) {
    var i;
    return {
      p: (function() {
        var _i, _ref, _results;
        _results = [];
        for (i = _i = 0, _ref = w.p.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
          _results.push((a.p[i] || 0) + (w.p[i] || 0));
        }
        return _results;
      })()
    };
  };

  cat = function(a, w) {
    return {
      p: a.p.concat(w.p)
    };
  };

  box = function(w) {
    return {
      p: [w.p],
      t: 1
    };
  };

  id = function(w) {
    return w;
  };

  from = function(a, w) {
    return {
      p: w.p.slice(a.p, +a.p + 1 || 9e9)
    };
  };

  size = function(w) {
    return {
      p: w.p.length
    };
  };

  rsh = function(a, w) {
    var i;
    return {
      p: (function() {
        var _i, _ref, _results;
        _results = [];
        for (i = _i = 0, _ref = a.p[0] - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
          _results.push(w.p[i % w.p.length]);
        }
        return _results;
      })()
    };
  };

  sha = function(w) {
    return {
      p: [w.t ? 0 : w.p.length]
    };
  };

  iota = function(w) {
    var i;
    return {
      p: (function() {
        var _i, _ref, _results;
        _results = [];
        for (i = _i = 0, _ref = w.p - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
          _results.push(i);
        }
        return _results;
      })()
    };
  };

  insert = function(a, w) {
    var i, z, _i, _ref;
    z = [
      {
        p: [w.p[w.p.length - 1]]
      }
    ];
    for (i = _i = _ref = w.p.length - 1; _i >= 1; i = _i += -1) {
      z.push(vd[a]({
        p: [w.p[i - 1]]
      }, z[z.length - 1]));
    }
    return z[z.length - 1];
  };

  vd = [0, plus, cat, 0, from, rsh, 0];

  vm = [0, id, 0, box, size, sha, iota];

  va = {
    '/': insert
  };

  noun = function(c) {
    if (c < '0' || c > '9') {
      return 0;
    } else {
      return {
        p: [c - '0'],
        t: 1
      };
    }
  };

  verb = function(c) {
    var i;
    return [
      (function() {
        var _i, _ref, _results;
        _results = [];
        for (i = _i = 0, _ref = vt.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
          if (vt[i] === c) {
            _results.push(i);
          }
        }
        return _results;
      })()
    ][0][0] || 0;
  };

  adverb = function(c) {
    return va[c];
  };

  wd = function(s) {
    var c, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = s.length; _i < _len; _i++) {
      c = s[_i];
      _results.push(noun(c) || verb(c) || c);
    }
    return _results;
  };

  val = function(x) {
    return !(typeof x === "object") && x !== void 0;
  };

  qv = function(c) {
    return val(c);
  };

  qp = function(c) {
    return val(c) && (c >= 'a' || c <= 'z');
  };

  st = {};

  ex = function(e, x) {
    var a;
    if (x == null) {
      x = 0;
    }
    a = e[x];
    if (qp(a)) {
      if (e[x + 1] === '=') {
        return st[a] = ex(e, x + 2);
      }
      a = st[a];
    }
    if (adverb(e[x + 1])) {
      return va[e[x + 1]](a, ex(e, x + 2));
    } else if (qv(a)) {
      return vm[a](ex(e, x + 1));
    } else if (val(e[x + 1])) {
      return vd[e[x + 1]](a, ex(e, x + 2));
    } else {
      return a;
    }
  };

  DEBUG = true;

  dbg = function(m) {
    if (DEBUG) {
      return console.log(m);
    }
  };

  test = function(m) {
    return console.log(m);
  };

  test2 = function(m, e) {
    var actual;
    actual = eval(m);
    if (actual + '' !== e + '') {
      console.log('TEST: ' + m + ' Failed.\nExpected/Actual:');
      console.log(e);
      return console.log(actual);
    }
  };

  DEBUG = false;

  test(ex(wd("5+1")).p[0] === 6);

  test(ex(wd("b=5")).p[0] === 5);

  test(ex(wd("+b")).p[0] === 5);

  ex(wd("a=3"));

  test(ex(wd("a+b")).p[0] === 8);

  test(ex(wd("q=1,2")).p.length === 2);

  test(ex(wd("m=2,4")).p.length === 2);

  test(ex(wd("+q")).p.length === 2);

  test(ex(wd("m+q")).p + '' === [3, 6] + '');

  test(ex(wd("m=2,4,6")).p + '' === [2, 4, 6] + '');

  test(ex(wd("z=<1,2")).p + '' === [[1, 2]] + '');

  test(ex(wd("z,z")).p + '' === [[1, 2], [1, 2]] + '');

  test(ex(wd("z,z")).p + '' === [[1, 2], [1, 2]] + '');

  test(ex(wd("{z,z")).p + '' === [2] + '');

  test(ex(wd("0{1,4")).p[0] === 1);

  test(ex(wd("1{1,4")).p[0] === 4);

  test(ex(wd("#1,2,3")).p[0] === 3);

  test(ex(wd("#<1,2,3")).p[0] === 0);

  test(ex(wd("#3")).p[0] === 0);

  test(ex(wd("2#1,2,3,4")).p + '' === '' + [1, 2]);

  test(ex(wd("4#1,2")).p + '' === '' + [1, 2, 1, 2]);

  test(ex(wd("z=<1,2")).p + '' === [[1, 2]] + '');

  test(ex(wd("1#<z")).p + '' === '' + [1, 2]);

  test(ex(wd("1#1,2")).p + '' === '' + [1]);

  test(ex(wd("~9")).p + '' === '' + [0, 1, 2, 3, 4, 5, 6, 7, 8]);

  test(ex(wd("~9+9")).p + '' === '' + [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]);

  test2("ex(wd('1+2+3+4')).p", [10]);

  test2("ex(wd('+/1,2,3,4')).p", [10]);

  test2("ex(wd('#/3,4,5')).p", [5, 5, 5]);

  test2("ex(wd('3#4#5')).p", [5, 5, 5]);

  test2("ex(wd('5#1')).p", [1, 1, 1, 1, 1]);

  test2("ex(wd(',/3,4,5')).p", [3, 4, 5]);

  test2("ex(wd('0{0{0')).p", [0]);

  test2("ex(wd('{/0,0,0')).p", [0]);

}).call(this);
